"""empty message

Revision ID: 252fa6c9dd3a
Revises: 
Create Date: 2021-07-09 03:34:17.401881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252fa6c9dd3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=2), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('contact1', sa.String(length=15), nullable=True),
    sa.Column('contact2', sa.String(length=15), nullable=True),
    sa.Column('contact3', sa.String(length=15), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('job', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('baptism', sa.String(length=10), nullable=False),
    sa.Column('baptismDay', sa.DateTime(), nullable=True),
    sa.Column('marriage', sa.String(length=5), nullable=False),
    sa.Column('prevChurch', sa.String(length=100), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('grade', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('member')
    # ### end Alembic commands ###
